# Generated by Django 4.1.6 on 2023-03-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/uploads/%Y/%m/%d/'),
        ),
    ]
